# -*- coding: utf-8 -*-
"""serlabs_waxalnlp_twi_asr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bd5l1sdaF43H8aj6qibljR1HEppf_wQP

# This task fine-tunes whisper small model for Twi transcription using the google/WaxalNLP (aka_asr) Dataset
"""

!pip install -U  evaluate jiwer transformers==4.52.0 -q
!pip install -U accelerate -q
!pip install --upgrade datasets==3.6.0 -q

"""ENVIRONMENT SETUP AND INSTALLATIONS

"""

from google.colab import userdata
hf_token=userdata.get('HF_TOKEN')

from huggingface_hub import login
login(token=hf_token)
print("logged in successfully")

"""LOAD MODEL AND PROCESSOR"""

from transformers import WhisperProcessor, WhisperForConditionalGeneration
import torch

# Load pre-trained model and processor
model_id = "openai/whisper-small"
processor = WhisperProcessor.from_pretrained(model_id)
model = WhisperForConditionalGeneration.from_pretrained(model_id)

# Move to GPU if available
device = "cuda" if torch.cuda.is_available() else "cpu"
model = model.to(device)

print(f"Model loaded on: {device}")

"""PREPARE DATASET"""

from datasets import load_dataset, DatasetDict


asr_data = DatasetDict()

# Load language data from WaxalNLP (aka_asr for Twi/Akan)
asr_data["train"] = load_dataset("google/WaxalNLP", "aka_asr", split="train", streaming=True)
asr_data["test"] = load_dataset("google/WaxalNLP", "aka_asr", split="test", streaming=True)

print(asr_data)
print(asr_data['train'].features)

import matplotlib.pyplot as plt
import librosa
import librosa.display

sample = next(iter(asr_data['train']))
audio_array=sample['audio']['array']
sampling_rate=sample['audio']['sampling_rate']
transcription_text=sample['transcription']

plt.figure(figsize=(14, 5))
librosa.display.waveshow(y=audio_array, sr=sampling_rate)
plt.title(f'Waveform: {transcription_text}')
plt.xlabel('Time (s)')
plt.ylabel('Amplitude')
plt.grid(True)
plt.tight_layout()
plt.show()

"""PREPROCESSING PIPELINE

Feature extraction with **WhisperFeatureExtractor**
"""

from transformers import WhisperFeatureExtractor

model_id = "openai/whisper-small"

feature_extractor = WhisperFeatureExtractor.from_pretrained(model_id)

"""Tokenization with **WhisperTokenizer**"""

from transformers import WhisperTokenizer

tokenizer = WhisperTokenizer.from_pretrained(model_id, language="yoruba", task="transcribe")

input_str = next(iter(asr_data["train"]))["transcription"]
labels = tokenizer(input_str).input_ids
decoded_with_special = tokenizer.decode(labels, skip_special_tokens=False)
decoded_str = tokenizer.decode(labels, skip_special_tokens=True)

print(f"Input:                 {input_str}")
print(f"Decoded w/ special:    {decoded_with_special}")
print(f"Decoded w/out special: {decoded_str}")
print(f"Are equal:             {input_str == decoded_str}")

"""Use **WhisperProcessor**"""

from transformers import WhisperProcessor

processor = WhisperProcessor.from_pretrained(model_id, language="yoruba", task="transcribe")

"""PREPARE DATA"""

import re
from datasets import Audio

# --- Constants ---
SAMPLING_RATE = 16000
CHARS_TO_IGNORE_REGEX = r'[\,\?\.\!\-\;\:\"\"\%\'\"\\]'
COLS_TO_REMOVE = ["id", "speaker_id", "language", "gender"]

# --- Preprocessing ---
for key in asr_data.keys():
    asr_data[key] = (
        asr_data[key]
        .remove_columns(COLS_TO_REMOVE)
        .cast_column("audio", Audio(sampling_rate=SAMPLING_RATE))
    )

def clean_transcription(text: str) -> str:
    """Lowercase and remove special characters from transcription."""
    return re.sub(CHARS_TO_IGNORE_REGEX, '', text).lower().strip() + " "

def prepare_dataset(batch):
    """Extract audio features and tokenize transcription."""
    audio = batch["audio"]

    batch["input_features"] = feature_extractor(
        audio["array"],
        sampling_rate=SAMPLING_RATE
    ).input_features[0]

    batch["labels"] = tokenizer(
        clean_transcription(batch["transcription"])
    ).input_ids

    return batch

print(next(iter(asr_data["train"])))

cols_to_remove = ["audio", "transcription"]

for key in asr_data.keys():
    asr_data[key] = asr_data[key].map(prepare_dataset, remove_columns=cols_to_remove)

"""TRAINING AND EVALUATION"""

from transformers import WhisperForConditionalGeneration

model = WhisperForConditionalGeneration.from_pretrained(model_id)

model.generation_config.language = "yoruba"
model.generation_config.task = "transcribe"

model.generation_config.forced_decoder_ids = None

import torch

from dataclasses import dataclass
from typing import Any, Dict, List, Union

@dataclass
class DataCollatorSpeechSeq2SeqWithPadding:
    processor: Any
    decoder_start_token_id: int

    def __call__(self, features: List[Dict[str, Union[List[int], torch.Tensor]]]) -> Dict[str, torch.Tensor]:
        # split inputs and labels since they have to be of different lengths and need different padding methods
        # first treat the audio inputs by simply returning torch tensors
        input_features = [{"input_features": feature["input_features"]} for feature in features]
        batch = self.processor.feature_extractor.pad(input_features, return_tensors="pt")

        # get the tokenized label sequences
        label_features = [{"input_ids": feature["labels"]} for feature in features]
        # pad the labels to max length
        labels_batch = self.processor.tokenizer.pad(label_features, return_tensors="pt")

        # replace padding with -100 to ignore loss correctly
        labels = labels_batch["input_ids"].masked_fill(labels_batch.attention_mask.ne(1), -100)

        # if bos token is appended in previous tokenization step,
        # cut bos token here as it's append later anyways
        if (labels[:, 0] == self.decoder_start_token_id).all().cpu().item():
            labels = labels[:, 1:]

        batch["labels"] = labels

        return batch

data_collator = DataCollatorSpeechSeq2SeqWithPadding(
    processor=processor,
    decoder_start_token_id=model.config.decoder_start_token_id,
)

import evaluate

metric = evaluate.load("wer")

def compute_metrics(pred):
    pred_ids = pred.predictions
    label_ids = pred.label_ids

    # replace -100 with the pad_token_id
    label_ids[label_ids == -100] = tokenizer.pad_token_id

    # we do not want to group tokens when computing the metrics
    pred_str = tokenizer.batch_decode(pred_ids, skip_special_tokens=True)
    label_str = tokenizer.batch_decode(label_ids, skip_special_tokens=True)

    wer = 100 * metric.compute(predictions=pred_str, references=label_str)

    return {"wer": wer}

import torch
from transformers import Seq2SeqTrainingArguments

training_args = Seq2SeqTrainingArguments(
    output_dir="./whisper_small-waxal_akan-asr",
    # Batch & gradient
    per_device_train_batch_size=16,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=2,
    gradient_checkpointing=True,
    # Precision
    fp16=torch.cuda.is_available(),
    # Learning rate & schedule
    learning_rate=1e-5,
    warmup_steps=100,
    max_steps=1000,
    optim="adamw_torch",
    # Evaluation & saving
    eval_strategy="steps",
    eval_steps=100,
    save_steps=100,
    save_total_limit=3,
    logging_steps=25,
    load_best_model_at_end=True,
    # Generation
    predict_with_generate=True,
    generation_max_length=225,
    # Metrics & reporting
    metric_for_best_model="wer",
    greater_is_better=False,
    report_to=["tensorboard"],
    # Data loading
    dataloader_num_workers=4,
    # Hub
    push_to_hub=True,
)

from transformers import Seq2SeqTrainer

trainer = Seq2SeqTrainer(
    args=training_args,
    model=model,
    train_dataset=asr_data["train"],
    eval_dataset=asr_data["test"],
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    processing_class=processor.feature_extractor,
)

"""Begin **Training**"""

trainer.train()

kwargs = {
    "dataset_tags": "google/WaxalNLP",
    "dataset": "WaxalNLP aka_asr",
    "dataset_args": "config: aka_asr, splits: [train, test]",
    "language": "yoruba",
    "model_name": "Whisper Small SerendepifyLabs Twi ASR",
    "finetuned_from": "openai/whisper-small",
    "tasks": "automatic-speech-recognition",
}

trainer.push_to_hub(**kwargs)
processor.push_to_hub("teckedd/whisper_small-waxal_akan-asr")

#!pip install -q --upgrade transformers==4.45.0 huggingface_hub

#!pip install -U transformers -q

"""MODEL USAGE"""

model_name="teckedd/whisper-small-serlabs-twi-asr"
from transformers import WhisperForConditionalGeneration, WhisperProcessor

model = WhisperForConditionalGeneration.from_pretrained(model_name)
processor = WhisperProcessor.from_pretrained(model_name,trust_remote_code=True)

"""DEMO"""

!pip install gradio -q

from transformers import pipeline
import gradio as gr

model_name = "teckedd/whisper_small-waxal_akan-asr"
device = 0  # GPU device, use -1 for CPU
pipe = pipeline(model=model_name, return_language=True, device=device)

def transcribe(audio):
    result = pipe(audio)
    text = result["text"]
    language = result.get("language", "Unknown")  # Extract language
    print(result)
    return f"Language: {language}\n\nText: {text}"


iface = gr.Interface(
    fn=transcribe,
    inputs=gr.Audio(sources=["microphone", "upload"], type="filepath"),
    outputs="text",
    title="Whisper Small Twi",
    description="Realtime demo for Twi speech recognition using a fine-tuned Whisper small model.",
)
iface.launch(share=True)